name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
            java-version: 8
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY_API}}
          heroku_app_name: cony-person-lab1
          heroku_email: conyyy833@gmail.com
      - name: Checkout test repository
        uses: actions/checkout@v2
        with:
          repository: Romanow/person-service-test
          path: integration-tests
          ref: master
      - uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: run test2
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-tests
          arguments: clean test -PtargetUrl=http://cony-person-lab1.herokuapp.com --info